// Русские тексты игры «Морской бой». Ключи games.battleship.* (название и описание для каталога добавятся при подключении к каталогу).
(function (root) {
  root.LOCALES = root.LOCALES || {};
  var p = 'games.battleship.';
  var texts = {
    'title': 'Морской бой',
    'sub': 'Двое по очереди стреляют по полю соперника. Кто первым потопит весь флот, тот и победил.',
    'toCatalog': 'В каталог',
    'back': 'Назад',
    'start.mode': 'Режим',
    'start.online': 'Онлайн, 2 игрока',
    'start.onlineSub': 'Стол по коду. Нужен вход через Google.',
    'start.play': 'Играть',
    'start.soon': 'Онлайн-столы появятся на следующем этапе.',
    'rules.button': 'Правила',
    'letters': 'АБВГДЕЖЗИК',
    'you': 'Вы',
    'foe': 'Соперник',
    'place.title': 'Расстановка',
    'place.hint': 'Выберите корабль и нажмите на поле. Нажмите на корабль на поле, чтобы взять его обратно.',
    'place.rotate': 'Повернуть',
    'place.random': 'Случайно',
    'place.clear': 'Очистить',
    'place.ready': 'Готов',
    'place.bad': 'Сюда нельзя: корабли не должны касаться друг друга',
    'place.left': 'Осталось расставить: {n}',
    'place.waiting': 'Ждём соперника…',
    'place.undo': 'Передумал',
    'ship.aria': 'Корабль из {len} клеток, осталось {n}',
    'battle.title': 'Бой',
    'turn.you': 'Ваш ход',
    'turn.foe': 'Ход соперника',
    'turn.hint': 'Нажмите на клетку соперника, потом «Огонь!»',
    'fire': 'Огонь!',
    'fire.pick': 'Выберите клетку',
    'last.you': 'Вы: {cell} — {res}',
    'last.foe': 'Соперник: {cell} — {res}',
    'res.miss': 'мимо',
    'res.hit': 'ранил',
    'res.sunk': 'убил',
    'board.mine': 'Ваше поле',
    'board.foe': 'Поле соперника',
    'left.foe': 'У соперника осталось',
    'over.win': 'Вы победили!',
    'over.lose': 'Вы проиграли',
    'over.win.fleet': 'Весь флот соперника потоплен.',
    'over.lose.fleet': 'Ваш флот потоплен.',
    'over.win.concede': 'Соперник сдался.',
    'over.lose.concede': 'Вы сдались.',
    'over.menu': 'В меню',
    'over.again': 'Сыграть ещё',
    'confirm.title': 'Сдаться?',
    'confirm.text': 'Партия будет засчитана как поражение.',
    'confirm.stay': 'Остаться',
    'confirm.ok': 'Сдаться',
    'exit.aria': 'Выйти',
    'rules.title': 'Правила',
    'rules.close': 'Закрыть',
    'rules.step1': 'У каждого поле 10 на 10 и флот: один корабль в четыре клетки, два в три, три в две и четыре в одну.',
    'rules.step2': 'Корабли стоят прямо и не касаются друг друга, даже углами.',
    'rules.step3': 'Игроки стреляют по очереди: выберите клетку чужого поля и нажмите «Огонь!».',
    'rules.step4': 'Попали или потопили корабль: стреляете ещё раз. Промах передаёт ход.',
    'rules.step5': 'Когда корабль потоплен, клетки вокруг него отмечаются точками. Выигрывает тот, кто первым потопил весь флот.',
    'theme.aria': 'Тема'
  };
  Object.keys(texts).forEach(function (k) { root.LOCALES.ru = root.LOCALES.ru || {}; root.LOCALES.ru[p + k] = texts[k]; });
})(typeof window !== 'undefined' ? window : globalThis);
