// Русские тексты игры «Покер». Ключи games.poker.* (название и описание для каталога лежат в locales/ru.js).
(function (root) {
  root.LOCALES = root.LOCALES || {};
  var p = 'games.poker.';
  var texts = {
    'title': 'Покер',
    'sub': 'Холдем с блайндами: двое слева от кнопки вносят ставки вслепую.',
    'toCatalog': 'В каталог',
    'back': 'Назад',
    'play': 'Играть',
    'rules': 'Правила',
    'unitShort': 'ак.',
    'you': 'Вы',
    'modeBots': 'С ботами',
    'setup.players': 'Игроков за столом',
    'setup.ante': 'Блайнды (малый/большой)',
    'setup.stack': 'Ваш стек: {n}',
    'setup.cap': 'Можно выиграть сегодня ещё: {n}.',
    'setup.broke': 'Аконов не хватает для большого блайнда {n}. Загляните за бонусом дня.',
    'setup.sit': 'Сесть за стол',
    'round.pre': 'Первый круг',
    'round.flop': 'Три общие карты',
    'round.turn': 'Четвёртая карта',
    'round.river': 'Последняя карта',
    'round.show': 'Вскрытие',
    'round.wait': 'Ждём раздачу',
    'pot': 'Банк {n}',
    'cap.next': 'Все походили: открываем карту',
    'cap.cut': 'Дневной предел выигрыша: начислено только +{n}.',
    'cap.reached': 'Дневной предел выигрыша достигнут: выигрыш не начислен.',
    'st.turn': 'Ходит',
    'st.yourTurn': 'Ваш ход',
    'st.wait': 'Ждёт',
    'st.fold': 'Сбросил',
    'st.call': 'Уравнял',
    'st.check': 'Пропустил',
    'st.raise': 'Повысил {n}',
    'st.bet': 'Поставил {n}',
    'st.allin': 'Ва-банк',
    'st.win': 'Победа',
    'st.ready': 'Готов',
    'st.out': 'Нет аконов',
    'st.left': 'Вышел',
    'act.fold': 'Сбросить',
    'act.call': 'Уравнять {n}',
    'act.check': 'Пропустить',
    'act.raise': 'Повысить',
    'act.betFrom': 'Поставить от {n}',
    'act.waitFor': 'Ходит {name}',
    'act.waitCard': 'Ждём открытия карты',
    'act.waitBot': 'Ходит соперник',
    'mand': 'Обязательный круг: пропускать нельзя',
    'bet.sum': 'Ставка {n}',
    'bet.reset': 'Сбросить ставку',
    'bet.pop': 'Убрать последнюю фишку',
    'bet.empty': 'Нажмите на фишки',
    'bet.allin': 'Ва-банк',
    'bet.min': 'Минимум {n}',
    'bet.short': ' · Не хватает до минимума',
    'bet.onlyAllin': 'Остаётся только ва-банк',
    'bet.cancel': 'Отмена',
    'bet.raise': 'Повысить',
    'bet.raiseTo': 'Повысить до {n}',
    'bet.betN': 'Поставить {n}',
    'confirm.foldTitle': 'Сбросить карты?',
    'confirm.foldText': 'Вы выйдете из этой раздачи, ставка останется в банке',
    'confirm.stay': 'Остаться',
    'confirm.fold': 'Сбросить',
    'confirm.allinTitle': 'Пойти ва-банк на {n}?',
    'confirm.allinText': 'Вы поставите все свои аконы',
    'confirm.cancel': 'Отмена',
    'confirm.allin': 'Ва-банк',
    'confirm.leaveTitle': 'Выйти из-за стола?',
    'confirm.leaveText': 'Ваши карты будут сброшены',
    'confirm.leave': 'Выйти',
    'menu.aria': 'Меню',
    'menu.rules': 'Правила',
    'menu.combos': 'Комбинации',
    'menu.leave': 'Выйти из-за стола',
    'sum.aria': 'Итог раздачи',
    'sum.bank': 'Банк: {n}',
    'sum.bet': 'Поставил {n}',
    'sum.betFold': 'Поставил {n}, сбросил',
    'sum.win': '★ Победа +{n}',
    'sum.main': 'Основной банк ({n}): ★ Победа {name} (+{win})',
    'sum.mainTie': 'Основной банк ({n}): делят банк {name} (+{win} каждому)',
    'sum.side': 'Побочный банк {k} ({n}): ★ Победа {name} (+{win})',
    'sum.sideTie': 'Побочный банк {k} ({n}): делят банк {name} (+{win} каждому)',
    'sum.returned': 'Возвращено {name} +{n}',
    'sum.takes': '{name} забирает банк +{n}',
    'sum.takesYou': 'Вы забираете банк +{n}',
    'sum.back': 'Вернуться к столу',
    'sum.leave': 'Выйти из-за стола',
    'broke.title': 'У вас не осталось аконов',
    'broke.text': 'Докупки за столом нет. Загляните за бонусом дня.',
    'broke.leave': 'Выйти из-за стола',
    'combos.title': 'Комбинации',
    'combos.close': 'Закрыть',
    'hand.royalFlush': 'Флеш-рояль',
    'hand.straightFlush': 'Стрит-флеш',
    'hand.quads': 'Каре',
    'hand.fullHouse': 'Фулл-хаус',
    'hand.flush': 'Флеш',
    'hand.straight': 'Стрит',
    'hand.trips': 'Тройка',
    'hand.twoPair': 'Две пары',
    'hand.pair': 'Пара',
    'hand.high': 'Старшая карта',
    'rules.title': 'Правила',
    'rules.close': 'Закрыть',
    'rules.step1': 'Каждому раздают по две карты. Ваши лежат лицом вверх, чужие рубашкой.',
    'rules.step2': 'Перед раздачей двое слева от кнопки ставят блайнды: малый и большой.',
    'rules.step3': 'Дальше по кругу: пропустить, уравнять, повысить, сбросить или ва-банк.',
    'rules.step4': 'Общих карт пять: три сразу, потом по одной. Карта открывается, когда все походили.',
    'rules.step5': 'Побеждает сильнейшая комбинация из пяти карт.',
    'rules.strength': 'Сила комбинаций, от сильной к слабой',
    'rules.mandTitle': 'Что такое блайнды',
    'rules.mandText': 'Блайнды — обязательные ставки вслепую, они запускают торги. Сейчас: малый {s}, большой {b}. Кнопка дилера (D) каждую раздачу сдвигается на одного игрока.',
    'mode.bots': 'С ботами',
    'mode.online': 'Онлайн',
    'login.need': 'Нужно войти',
    'login.text': 'Онлайн-столы доступны после входа через Google.',
    'login.btn': 'Войти через Google',
    'login.busy': 'Входим…',
    'online.title': 'Онлайн',
    'online.create': 'Создать стол',
    'online.code': 'Код стола',
    'online.paste': 'Вставить',
    'online.join': 'Войти',
    'online.codeHint': '5 символов: латинские буквы и цифры',
    'online.codeMore': 'Ещё {n} символов',
    'online.codeBad': '✕ Неверный код. Проверьте 5 символов',
    'online.open': 'Открытые столы',
    'online.empty': 'Открытых столов пока нет. Создайте свой.',
    'online.count': '{n} из {m}',
    'online.taken': 'Занят',
    'online.enter': 'Войти',
    'online.busy': 'Подключаемся…',
    'net.wake': 'Подключаемся к серверу… он может проснуться не сразу',
    'net.lost': 'Нет связи, переподключаемся…',
    'net.back': 'Связь восстановлена',
    'create.title': 'Новый стол',
    'create.seats': 'Число мест',
    'create.closed': 'Закрытый стол',
    'create.closedSub': 'Только по коду или ссылке',
    'create.go': 'Создать стол',
    'wait.title': 'Комната ожидания',
    'wait.code': 'Код стола',
    'wait.copy': 'Скопировать код',
    'wait.copied': 'Скопировано',
    'wait.share': 'Поделиться ссылкой',
    'wait.params': 'Блайнды {s}/{b}',
    'wait.leave': 'Выйти',
    'wait.start': 'Начать игру',
    'wait.in': 'Можно начать через {n}…',
    'wait.guest': 'Ждём, пока создатель начнёт',
    'wait.free': 'Ждём игрока…',
    'wait.creator': 'Создатель',
    'wait.private': 'Закрытый стол',
    'chat': 'Чат',
    'err.notFound': 'Стол не найден',
    'err.notFoundText': 'Такого кода нет. Проверьте код и попробуйте ещё раз.',
    'err.full': 'Стол заполнен',
    'err.fullText': 'Все места заняты. Выберите другой стол.',
    'err.started': 'Игра на этом столе уже идёт',
    'err.startedText': 'Подождите конца раздачи или выберите другой стол.',
    'err.closed': 'Стол закрыт',
    'err.closedText': 'Создатель закрыл стол или все вышли.',
    'err.other': 'Не получилось',
    'err.otherText': 'Проверьте связь и попробуйте ещё раз.',
    'err.toPick': 'К выбору стола',
    'ask.title': 'Вы ещё играете?',
    'ask.text': 'Без ответа будет сыграно автоматически: Пропустить или Сбросить.',
    'ask.yes': 'Да, играю',
    'ask.leave': 'Выйти из-за стола',
    'ask.autoTitle': 'Время вышло',
    'ask.autoText': 'Поставлено автоматически: Пропустить или Сбросить.',
    'ask.ok': 'Продолжить',
    'ask.outTitle': 'Вы выбыли из-за стола',
    'ask.outText': 'Вы не отвечали несколько раз подряд. Можно вернуться к выбору стола.',
    'ready.wait': 'Ждём остальных: {n} из {m} готовы',
    'ready.left': 'Следующая раздача не позже чем через {n}…',
    'ready.me': 'Вы готовы',
    'toast.joined': 'Игрок {name} сел за стол',
    'toast.left': 'Игрок {name} вышел',
    'st.skip': 'Пропускает',
    'act.sent': 'Отправляем ход…',
    'ask.toPick': 'К списку столов',
    'confirm.leaveOnlineText': 'Ваши карты будут сброшены',
    'suit.S': '♠', 'suit.H': '♥', 'suit.D': '♦', 'suit.C': '♣'
  };
  root.LOCALES.ru = root.LOCALES.ru || {};
  Object.keys(texts).forEach(function (k) { root.LOCALES.ru[p + k] = texts[k]; });
})(typeof window !== 'undefined' ? window : globalThis);
