// Русские тексты игры «Блэкджек». Ключи games.blackjack.* (название и описание для каталога лежат в locales/ru.js).
(function (root) {
  root.LOCALES = root.LOCALES || {};
  var p = 'games.blackjack.';
  var texts = {
    'toCatalog': 'В каталог',
    'rules': 'Правила',
    'rulesBtn': 'Правила',
    'themeBtn': 'Сменить тему',
    'close': 'Закрыть',
    'back': 'Назад',
    'cancel': 'Отмена',
    'tagline': 'Наберите больше дилера, но не больше 21',
    'balance': 'Баланс: {n} {unit}',
    'balanceShort': '{n} ак.',
    'balanceFull': '{n} {unit}',
    'modeBot': 'С ботом',
    'modeBotSub': '1 на 1, сразу',
    'modeOnline': 'Онлайн',
    'modeOnlineSub': '2–5 игроков, по коду',
    'poor.title': 'Аконов не хватает на ставку',
    'poor.text': 'Минимальная ставка — {n}. Получить аконы: бонус дня, награды за победы в «Сапёре» и «Ятзи».',
    'poor.claim': 'Забрать бонус дня',
    'botName': 'Бот Ро',
    'you': 'Вы',
    'youBal': 'Вы · {n}',
    'dealer': 'Дилер',

    'login.title': 'Для онлайна нужно войти',
    'login.text': 'Так мы узнаём, кто за столом.',
    'login.btn': 'Войти через Google',
    'login.busy': 'Входим…',
    'login.error': 'Не удалось войти. Попробуйте ещё раз.',
    'login.unsupported': 'Вход сейчас недоступен: нужен сайт по https и подключение к интернету.',
    'login.domain': 'Адрес этого сайта не добавлен в разрешённые домены Firebase.',
    'login.popup': 'Браузер заблокировал окно входа. Разрешите всплывающие окна и попробуйте снова.',

    'tables.title': 'Онлайн-столы',
    'tables.create': 'Создать стол',
    'tables.codeTitle': 'Войти по коду',
    'tables.codeLabel': 'Код стола',
    'tables.paste': 'Вставить',
    'tables.join': 'Войти',
    'tables.open': 'Открытые столы',
    'tables.loading': 'Ищем столы…',
    'tables.empty': 'Открытых столов пока нет, создайте свой',
    'tables.of': '{n} из {m}',
    'tables.you': 'Вы: {name}',
    'err.notFound': 'Стол не найден',
    'err.notFoundText': 'Проверьте код: 5 символов',
    'err.full': 'Стол заполнен',
    'err.fullText': 'Все места заняты',
    'err.closed': 'Игра уже закончилась',
    'err.closedText': 'Создайте новый стол',
    'err.network': 'Нет связи',
    'err.networkText': 'Проверьте интернет и попробуйте снова',
    'err.denied': 'Нет доступа к столам',
    'err.deniedText': 'Войдите снова или проверьте правила базы',
    'err.other': 'Что-то пошло не так',
    'err.otherText': 'Попробуйте ещё раз',
    'err.hostGone': 'Создатель вышел, стол закрыт',
    'err.toTables': 'К выбору стола',
    'err.shortCode': 'Код состоит из 5 символов',

    'create.title': 'Новый стол',
    'create.seats': 'Сколько мест',
    'create.bots': 'Заполнить пустые места ботами',
    'create.botsSub': 'Игра начнётся сразу',
    'create.botsOff': 'Только живые игроки, нужно минимум двое',
    'create.btn': 'Создать',
    'create.busy': 'Создаём…',

    'lobby.title': 'Комната ожидания',
    'lobby.code': 'Код стола',
    'lobby.copy': 'Скопировать код',
    'lobby.copied': 'Скопировано',
    'lobby.share': 'Поделиться ссылкой',
    'lobby.start': 'Начать игру',
    'lobby.needMore': 'Нужен ещё игрок',
    'lobby.leave': 'Выйти',
    'lobby.close': 'Закрыть стол',
    'lobby.waitHost': 'Ждём, пока создатель начнёт',
    'lobby.creator': 'Создатель',
    'lobby.you': 'Вы',
    'lobby.waiting': 'Ждём игрока',
    'lobby.bot': 'Бот',
    'lobby.hostHint': 'Не закрывайте эту вкладку, пока идёт игра',

    'bet.note': 'Макс. {max} · нажмите «Раздать»',
    'bet.noteOnline': 'Макс. {max} · нажмите «Поставить»',
    'bet.maxNote': 'Максимум {max}: фишки недоступны',
    'bet.poorNote': 'Аконов не хватает на большую ставку',
    'bet.title': 'Ставка {n}',
    'bet.chip': 'Фишка {n}',
    'bet.chipOff': 'Фишка {n}, недоступна',
    'bet.clear': 'Очистить',
    'bet.deal': 'Раздать',
    'bet.place': 'Поставить',
    'bet.cancel': 'Отменить ставку',
    'bet.placed': 'Ставка принята',
    'bet.ready': '{n} из {m} поставили',
    'bet.sit': 'Пропустить раздачу',
    'bet.sitting': 'Вы пропускаете раздачу',
    'bet.back': 'Вернуться за стол',

    'st.bets': 'Ставит…',
    'st.betsDone': 'Поставил(а) {n}',
    'st.skips': 'Пропускает',
    'st.thinks': 'Думает',
    'st.thinksSec': 'Думает · {n} с',
    'st.stand': 'Стоп',
    'st.bust': 'Перебор',
    'st.bj': 'Блэкджек!',
    'st.waits': 'Ждёт',
    'st.silent': 'Не отвечает…',
    'st.left': 'Вышел',
    'st.bot': 'Бот',
    'sum.soft': 'Мягкие {n}',
    'sum.bust': 'Перебор {n}',
    'sum.bj': 'Блэкджек!',
    'turn.you': 'Ваш ход',
    'turn.youSec': 'Ваш ход · {n} с',
    'turn.other': 'Ходит {name}',
    'act.hit': 'Взять',
    'act.stand': 'Стоп',
    'act.hint': 'Подсказка',
    'act.sending': 'Отправлено…',
    'key.hit': 'Пробел · H',
    'key.stand': 'S',
    'hint.dealerWeak': 'У дилера {up}: он, скорее всего, перебьёт. Остановитесь.',
    'hint.enough': 'У вас {total}: брать опасно. Остановитесь.',
    'hint.hit': 'У вас {total}, а у дилера {up}: он может набрать больше. Берите карту.',
    'hint.softHit': 'У вас мягкие {total}: перебор невозможен с одной картой. Берите карту.',

    'res.win': 'Вы выиграли',
    'res.bj': 'Блэкджек!',
    'res.push': 'Равно',
    'res.lose': 'Вы проиграли',
    'res.bust': 'Перебор',
    'res.dealerBj': 'У дилера блэкджек',
    'res.subWin': 'Ставка {bet} · выплата 1:1',
    'res.subBj': 'Выплата 3:2',
    'res.subPush': 'Ставка {bet} возвращена',
    'res.subLose': '{a} против {b}',
    'res.subBust': 'Больше 21 — сразу проигрыш',
    'res.subDealerBj': 'Раздача закончилась сразу',
    'res.delta.plus': '+{n} {unit}',
    'res.delta.minus': '−{n} {unit}',
    'res.delta.zero': '±0 аконов',
    'res.beatBot': 'Вы обыграли бота',
    'res.botBeat': 'Бот выиграл больше',
    'res.even': 'Поровну',
    'res.rows': 'Вы {a} · Бот {b}',
    'res.again': 'Ещё раз · ставка {n}',
    'res.change': 'Изменить ставку',
    'res.broke': 'Аконов не хватает на следующую ставку.',
    'res.brokeText': 'Бонус дня и награды в «Сапёре» и «Ятзи» пополнят баланс.',
    'res.nextIn': 'Новая раздача через {n} с',
    'res.leave': 'Выйти из-за стола',
    'res.toCatalog': 'В каталог',
    'res.mini': '{d} {unit}',

    'ask.title': 'Вы ещё играете?',
    'ask.secs': 'секунд до автоматического «Стоп»',
    'ask.secsBet': 'секунд до пропуска раздачи',
    'ask.yes': 'Да, играю',
    'ask.leave': 'Выйти из-за стола',
    'notice.extended': 'Вы ответили «Да, играю»: ещё 15 секунд на ход',
    'notice.auto': 'Время вышло: автоматически поставлен «Стоп»',
    'notice.shuffle': 'Колода перетасована',
    'notice.kicked': 'Вы выбыли из-за стола: три пропуска подряд',
    'notice.broke': 'Аконов не хватает на ставку, раздача будет пропущена',
    'banner.offline': 'Нет связи, переподключаемся…',
    'banner.back': 'Связь восстановлена',
    'banner.hostGone': 'Создатель стола вышел',
    'banner.relogin': 'Нужно войти снова',

    'rules.title': 'Правила',
    'rules.goal.title': 'Цель',
    'rules.goal.text': 'Набрать больше очков, чем у дилера, но не больше 21.',
    'rules.cards.title': 'Карты',
    'rules.cards.text': '2–10 по номиналу, J, Q, K — 10, туз — 1 или 11.',
    'rules.turn.title': 'Ход',
    'rules.turn.text': 'Вам две карты открыто, дилеру одна. «Взять» — ещё карта, «Стоп» — хватит.',
    'rules.pay.title': 'Выплаты',
    'rules.pay.text': 'Блэкджек (туз и десятка) — 3:2, обычный выигрыш — 1:1, «Равно» — ставка возвращается.',
    'rules.dealer.title': 'Дилер',
    'rules.dealer.text': 'Берёт до 17 и останавливается на любых 17.',
    'rules.ok': 'Понятно',

    'confirmCatalog.title': 'Выйти в каталог?',
    'confirmCatalog.text': 'Ставка текущей раздачи будет потеряна',
    'confirmTable.title': 'Выйти из-за стола?',
    'confirmTable.text': 'Ваша рука в текущей раздаче останется как есть',
    'confirmClose.title': 'Закрыть стол?',
    'confirmClose.text': 'Если вы выйдете, стол закроется для всех',
    'confirm.stay': 'Остаться',
    'confirm.leave': 'Выйти',
    'confirm.closeTable': 'Закрыть стол',

    'card.down': 'Карта рубашкой вверх',
    'card.name': '{rank}, {suit}',
    'suit.s': 'пики',
    'suit.c': 'трефы',
    'suit.h': 'червы',
    'suit.d': 'бубны'
  };
  root.LOCALES.ru = root.LOCALES.ru || {};
  Object.keys(texts).forEach(function (k) { root.LOCALES.ru[p + k] = texts[k]; });
})(typeof window !== 'undefined' ? window : globalThis);
