// Русские тексты игры «Блэкджек». Ключи games.blackjack.* (название и описание для каталога лежат в locales/ru.js).
(function (root) {
  root.LOCALES = root.LOCALES || {};
  var p = 'games.blackjack.';
  var texts = {
    'toCatalog': 'В каталог',
    'rules': 'Правила',
    'rulesBtn': 'Правила',
    'themeBtn': 'Сменить тему',
    'close': 'Закрыть',
    'back': 'Назад',
    'cancel': 'Отмена',
    'tagline': 'Наберите больше дилера, но не больше 21',
    'balance': 'Баланс: {n} {unit}',
    'balanceShort': '{n} ак.',
    'balanceFull': '{n} {unit}',
    'start.mode': 'Режим',
    'start.play': 'Играть',
    'modeBot': 'С ботом',
    'modeBotSub': 'против дилера, без ставок',
    'modeOnline': 'Онлайн',
    'modeOnlineSub': '2–5 игроков, по коду, без ставок',
    'you': 'Вы',
    'dealer': 'Дилер',

    'login.title': 'Для онлайна нужно войти',
    'login.text': 'Так мы узнаём, кто за столом.',
    'login.btn': 'Войти через Google',
    'login.busy': 'Входим…',
    'login.error': 'Не удалось войти. Проверьте соединение и попробуйте снова.',
    'login.retry': 'Попробовать снова',
    'login.unsupported': 'Вход сейчас недоступен: нужен сайт по https и подключение к интернету.',
    'login.domain': 'Адрес этого сайта не добавлен в разрешённые домены Firebase.',
    'login.popup': 'Браузер заблокировал окно входа. Разрешите всплывающие окна и попробуйте снова.',

    'tables.title': 'Онлайн-столы',
    'tables.create': 'Создать стол',
    'tables.codeTitle': 'Войти по коду',
    'tables.codeLabel': 'Код стола',
    'tables.paste': 'Вставить',
    'tables.join': 'Войти',
    'tables.open': 'Открытые столы',
    'tables.loading': 'Ищем столы…',
    'tables.empty': 'Открытых столов пока нет, создайте свой',
    'tables.of': '{n} из {m}',
    'tables.bots': 'с ботами',
    'tables.you': '{name}',
    'err.notFound': 'Стол не найден',
    'err.notFoundText': 'Проверьте код: 5 символов',
    'err.full': 'Стол заполнен',
    'err.fullText': 'Все места заняты',
    'err.closed': 'Игра уже закончилась',
    'err.closedText': 'Создайте новый стол',
    'err.network': 'Нет связи',
    'err.networkText': 'Проверьте интернет и попробуйте снова',
    'err.missing': 'База данных не найдена',
    'err.missingText': 'Столы сейчас недоступны, сообщите владельцу сайта',
    'err.denied': 'Нет доступа к столам',
    'err.deniedText': 'Войдите снова или проверьте правила базы',
    'err.other': 'Что-то пошло не так',
    'err.otherText': 'Попробуйте ещё раз',
    'err.hostGone': 'Создатель вышел, стол закрыт',
    'err.toTables': 'К выбору стола',
    'err.shortCode': 'Код состоит из 5 символов',

    'create.title': 'Новый стол',
    'create.seats': 'Сколько мест',
    'create.bots': 'Заполнить пустые места ботами',
    'create.botsSub': 'Игра начнётся сразу, даже если никто не пришёл',
    'create.botsOff': 'Только живые игроки, нужно минимум двое',
    'create.private': 'Закрытый стол',
    'create.privateSub': 'Не виден в списке: войти можно только по коду или ссылке',
    'create.privateOff': 'Виден в списке открытых столов',
    'create.btn': 'Создать стол',
    'create.previewBots': 'Вы и {n} бот(а): игра начнётся сразу',
    'create.previewFree': 'Вы и {n} {w}: ждём игроков',
    'create.dealer': 'Дилер',
    'create.seatWord.one': 'место',
    'create.seatWord.few': 'места',
    'create.seatWord.many': 'мест',
    'create.you': 'Вы',
    'create.busy': 'Создаём…',

    'lobby.title': 'Комната ожидания',
    'lobby.private': 'Закрытый стол: только по коду или ссылке',
    'lobby.code': 'Код стола',
    'lobby.copy': 'Скопировать код',
    'lobby.copied': 'Скопировано ✓',
    'lobby.full': 'Стол заполнен · ждём, пока создатель начнёт',
    'lobby.share': 'Поделиться ссылкой',
    'lobby.start': 'Начать игру',
    'lobby.needMore': 'Нужен ещё игрок',
    'lobby.leave': 'Выйти',
    'lobby.close': 'Закрыть стол',
    'lobby.waitHost': 'Ждём, пока создатель начнёт',
    'lobby.creator': 'Создатель',
    'lobby.you': 'Вы',
    'lobby.waiting': 'Ждём игрока',
    'lobby.bot': 'Бот',
    'lobby.startIn': 'Начать можно через {n} с',
    'lobby.hostHint': 'Не закрывайте эту вкладку, пока идёт игра',


    'st.deals': 'Раздача',
    'wait.dealing': 'Раздаём карты…',
    'st.skips': 'Пропускает',
    'st.thinks': 'Думает',
    'st.thinksSec': 'Думает · {n} с',
    'st.stand': 'Стоп',
    'st.bust': 'Перебор',
    'st.bj': 'Блэкджек!',
    'st.waits': 'Ждёт',
    'st.silent': 'Не отвечает…',
    'st.left': 'Вышел',
    'st.bot': 'Бот',
    'cap.left': 'Можно получить наград сегодня ещё: {n}.',
    'cap.cut': 'Дневной предел наград: начислено только +{n}.',
    'cap.reached': 'Дневной предел наград достигнут: награда не начислена.',
    'sum.soft': 'Мягкие {n}',
    'sum.bust': 'Перебор {n}',
    'sum.bj': 'Блэкджек!',
    'turn.you': 'Ваш ход',
    'turn.youSec': 'Ваш ход · {n} с',
    'turn.other': 'Ходит {name}',
    'act.hit': 'Взять',
    'act.stand': 'Стоп',
    'act.sending': 'Отправлено…',
    'key.hit': 'Пробел · H',
    'key.stand': 'S',

    'res.win': 'Вы выиграли',
    'res.bj': 'Блэкджек!',
    'res.push': 'Равно',
    'res.lose': 'Вы проиграли',
    'res.bust': 'Перебор',
    'res.dealerBj': 'У дилера блэкджек',
    'res.subWin': 'Награда за победу',
    'res.subBj': 'Награда за блэкджек',
    'res.subPush': 'Ничья: награды нет',
    'res.subLose': '{a} против {b}',
    'res.subBust': 'Больше 21 — сразу проигрыш',
    'res.subDealerBj': 'Раздача закончилась сразу',
    'res.delta.plus': '+{n} {unit}',
    'res.delta.zero': '±0 аконов',
    'res.newBet': 'Следующая раздача',
    'res.back': 'Назад',
    'res.broke': 'Аконов не хватает на следующую ставку.',
    'res.brokeText': 'Бонус дня и награды в «Сапёре» и «Ятзи» пополнят баланс.',
    'res.nextIn': 'Новая раздача через {n} с',
    'res.leave': 'Выйти из-за стола',
    'res.toCatalog': 'В каталог',
    'res.mini': '{d} {unit}',

    'ask.title': 'Вы ещё играете?',
    'ask.secs': 'секунд до автоматического «Стоп»',
    'ask.secsBet': 'секунд до пропуска раздачи',
    'ask.yes': 'Да, играю',
    'ask.leave': 'Выйти из-за стола',
    'notice.extended': 'Вы ответили «Да, играю»: ещё 15 секунд на ход',
    'notice.auto': 'Время вышло: автоматически поставлен «Стоп»',
    'notice.shuffle': 'Колода перетасована',
    'notice.kicked': 'Вы выбыли из-за стола: три пропуска подряд',
    'out.title': 'Вы выбыли из-за стола',
    'out.text': 'Три автоматических хода подряд (3 пропуска). Баланс сохранён.',
    'out.btn': 'К выбору стола',
    'notice.creator': 'Вы создатель: не закрывайте эту вкладку, пока идёт игра',
    'wait.sent': 'Отправлено…',
    'wait.offline': 'Ждём соединения…',
    'banner.server': 'Подключаемся к серверу… он может проснуться не сразу',
    'banner.offline': 'Нет связи, переподключаемся…',
    'banner.back': 'Связь восстановлена',
    'banner.hostGone': 'Создатель стола вышел',
    'banner.relogin': 'Нужно войти снова',
    'banner.reloginBtn': 'Войти',

    'rules.title': 'Правила',
    'rules.goal.title': 'Цель',
    'rules.goal.text': 'Набрать больше очков, чем у дилера, но не больше 21.',
    'rules.cards.title': 'Карты',
    'rules.cards.text': '2–10 по номиналу, J, Q, K — 10, туз — 1 или 11.',
    'rules.turn.title': 'Ход',
    'rules.turn.text': 'Вам две карты открыто, дилеру одна. «Взять» — ещё карта, «Стоп» — хватит.',
    'rules.pay.title': 'Выплаты',
    'rules.pay.text': 'Блэкджек (туз и десятка) — 3:2, обычный выигрыш — 1:1, «Равно» — ставка возвращается.',
    'rules.dealer.title': 'Дилер',
    'rules.dealer.text': 'Берёт до 17 и останавливается на любых 17.',
    'rules.ok': 'Понятно',

    'confirmCatalog.title': 'Выйти в каталог?',
    'confirmCatalog.text': 'Ставка текущей раздачи будет потеряна',
    'confirmTable.title': 'Выйти из-за стола?',
    'confirmTable.text': 'Ваша рука в текущей раздаче останется как есть',
    'confirmClose.title': 'Закрыть стол?',
    'confirmClose.text': 'Если вы выйдете, стол закроется для всех',
    'confirm.stay': 'Остаться',
    'confirm.leave': 'Выйти',
    'confirm.closeTable': 'Закрыть стол',

    'card.down': 'Карта рубашкой вверх',
    'card.name': '{rank}, {suit}',
    'suit.s': 'пики',
    'suit.c': 'трефы',
    'suit.h': 'червы',
    'suit.d': 'бубны'
  };
  root.LOCALES.ru = root.LOCALES.ru || {};
  Object.keys(texts).forEach(function (k) { root.LOCALES.ru[p + k] = texts[k]; });
})(typeof window !== 'undefined' ? window : globalThis);
