// Русские тексты игры «Ятзи». Ключи games.yahtzee.* (название и описание для каталога лежат в locales/ru.js, там же games.yahtzee.title).
(function (root) {
  root.LOCALES = root.LOCALES || {};
  var p = 'games.yahtzee.';
  var texts = {
    'toCatalog': 'В каталог',
    'close': 'Закрыть',
    'cancel': 'Отмена',
    'turn': 'Ход',
    'newGame': 'Новая игра',
    'player1': 'Игрок 1',
    'player2': 'Игрок 2',
    'computer': 'Компьютер',
    'rollsLeft': 'Осталось бросков: {n}',

    'start.mode': 'Режим',
    'start.modeCpu': 'Против компьютера',
    'start.modeHot': 'Вдвоём на одном устройстве',
    'start.level': 'Сложность',
    'start.levelEasy': 'Лёгкий',
    'start.levelHard': 'Сильный',
    'start.players': 'Игроки',
    'start.name1': 'Имя первого игрока',
    'start.name2': 'Имя второго игрока',
    'start.modeOnline': 'Онлайн, 2–6 игроков',
    'start.onlineSub': 'Стол по коду: все играют одновременно или по очереди. Нужен вход через Google.',
    'start.play': 'Играть',

    'status.thinking': 'Компьютер думает…',
    'status.rolling': 'Бросок…',
    'status.first': 'Бросьте кубики',
    'status.pick': 'Выберите клетку для записи',
    'status.holdOrRoll': 'Зафиксируйте кубики или бросьте ещё',

    'roll.cpuTurn': 'Ход компьютера',
    'roll.first': 'Бросить',
    'roll.more': 'Бросить ещё ({n})',
    'roll.none': 'Бросков не осталось',

    'die.fresh': 'Кубик {n}, не брошен',
    'die.value': 'Кубик {n}: {v}',
    'die.held': 'Кубик {n}: {v}, зафиксирован',
    'die.tag': 'ДЕРЖУ',

    'cat.ones': 'Единицы', 'cat.twos': 'Двойки', 'cat.threes': 'Тройки',
    'cat.fours': 'Четвёрки', 'cat.fives': 'Пятёрки', 'cat.sixes': 'Шестёрки',
    'cat.threeKind': 'Сет', 'cat.fourKind': 'Каре', 'cat.fullHouse': 'Фулл-хаус',
    'cat.smallStraight': 'Малый стрит', 'cat.largeStraight': 'Большой стрит',
    'cat.yahtzee': 'Ятзи', 'cat.chance': 'Шанс',

    'cell.filled': '{name}: {v}',
    'cell.write': 'Записать в «{name}»: {v}',
    'cell.blocked': '{name}: недоступно (жокер)',
    'cell.empty': '{name}: пусто',

    'sheet.upper': 'Верхняя секция',
    'sheet.lower': 'Нижняя секция',
    'sheet.sum': 'Сумма',
    'sheet.bonus': 'Бонус +35',
    'sheet.yahtzeeBonus': 'Ятзи +100',
    'sheet.total': 'Итого',

    'over.title': 'Игра окончена',
    'over.aria': 'Конец игры',
    'over.draw': 'Ничья',
    'over.winner': 'Победил: {name}',
    'over.toMenu': 'В меню',
    'over.again': 'Играть снова',
    'reward.earned': 'Награда за победу: +{n} {unit}',
    'reward.limit': 'Дневной лимит наград исчерпан, завтра снова.',

    'rules.button': 'Правила',
    'rules.title': 'Правила',
    'rules.turn.title': 'Ход',
    'rules.turn.text': 'До трёх бросков за ход. Нажмите на кубик, чтобы зафиксировать его — он не перебрасывается. В конце хода запишите результат ровно в одну свободную клетку. Игра идёт, пока не заполнены все 13 клеток.',
    'rules.upper.title': 'Верхняя секция',
    'rules.upper.text': 'Единицы–шестёрки: сумма кубиков с нужной гранью. Если сумма секции 63 и больше — бонус +35.',
    'rules.lower.title': 'Нижняя секция',
    'rules.lower.text': 'Сет (3 одинаковых) и каре (4) — сумма всех кубиков. Фулл-хаус 3+2 — 25. Малый стрит (4 подряд) — 30. Большой стрит (5 подряд) — 40. Ятзи (5 одинаковых) — 50. Шанс — сумма всех кубиков. Не получилось — запишите 0.',
    'rules.joker.title': 'Повторный ятзи и жокер',
    'rules.joker.text': 'Если «Ятзи» уже стоит 50, каждый новый ятзи даёт +100. Когда клетка «Ятзи» занята, действует жокер: сначала верхняя клетка этой грани; если занята — любая свободная нижняя (фулл-хаус и стриты дают полные очки); если и их нет — любая верхняя.',
    'rules.total.title': 'Итог',
    'rules.total.text': 'Обе секции плюс бонусы. Побеждает больший счёт.',

    'confirm.aria': 'Новая игра',
    'confirm.title': 'Начать заново?',
    'confirm.text': 'Текущая партия будет потеряна.',
    'confirm.ok': 'Начать заново',

    'exit.aria': 'Выйти в меню',
    'exit.title': 'Выйти в меню?',
    'exit.stay': 'Остаться',
    'exit.ok': 'Выйти',

    'online.back': 'Назад',
    'online.modeSync': 'Одновременно',
    'online.modeTurns': 'По очереди',
    'online.login.title': 'Для онлайна нужно войти',
    'online.login.text': 'Так мы узнаём, кто за столом.',
    'online.login.btn': 'Войти через Google',
    'online.login.busy': 'Входим…',
    'online.login.retry': 'Попробовать снова',
    'online.login.error': 'Не удалось войти. Проверьте соединение и попробуйте снова.',
    'online.login.unsupported': 'Вход сейчас недоступен: нужен сайт по https и подключение к интернету.',
    'online.login.domain': 'Адрес этого сайта не добавлен в разрешённые домены Firebase.',
    'online.login.popup': 'Браузер заблокировал окно входа. Разрешите всплывающие окна и попробуйте снова.',
    'online.tables.title': 'Онлайн-столы',
    'online.tables.you': 'Вы: {name}',
    'online.tables.create': 'Создать стол',
    'online.tables.codeTitle': 'Войти по коду',
    'online.tables.codeLabel': 'Код стола',
    'online.tables.paste': 'Вставить',
    'online.tables.join': 'Войти',
    'online.tables.open': 'Открытые столы',
    'online.tables.loading': 'Ищем столы…',
    'online.tables.empty': 'Открытых столов пока нет, создайте свой',
    'online.tables.of': '{n} из {m}',
    'online.err.notFound': 'Стол не найден',
    'online.err.notFoundText': 'Проверьте код: 5 символов',
    'online.err.full': 'Стол заполнен',
    'online.err.fullText': 'Все места заняты',
    'online.err.closed': 'Игра уже закончилась',
    'online.err.closedText': 'Создайте новый стол',
    'online.err.started': 'Игра уже началась',
    'online.err.startedText': 'Присоединиться можно только до начала',
    'online.err.network': 'Нет связи',
    'online.err.networkText': 'Проверьте интернет и попробуйте снова',
    'online.err.missing': 'База данных не найдена',
    'online.err.missingText': 'Столы сейчас недоступны, сообщите владельцу сайта',
    'online.err.denied': 'Нет доступа к столам',
    'online.err.deniedText': 'Войдите снова или проверьте правила базы',
    'online.err.other': 'Что-то пошло не так',
    'online.err.otherText': 'Попробуйте ещё раз',
    'online.err.hostGone': 'Создатель вышел, стол закрыт',
    'online.err.toTables': 'К выбору стола',
    'online.err.shortCode': 'Код состоит из 5 символов',
    'online.create.title': 'Новый стол',
    'online.create.seats': 'Сколько игроков',
    'online.create.you': 'Вы',
    'online.create.mode': 'Как играем',
    'online.create.syncSub': 'Все бросают сразу. Следующий раунд начинается, когда каждый записал очки.',
    'online.create.turnsSub': 'Ходит один игрок, остальные ждут своей очереди.',
    'online.create.btn': 'Создать стол',
    'online.create.busy': 'Создаём…',
    'online.lobby.title': 'Комната ожидания',
    'online.lobby.code': 'Код стола',
    'online.lobby.seats': '{n} мест',
    'online.lobby.copy': 'Скопировать код',
    'online.lobby.copied': 'Скопировано ✓',
    'online.lobby.share': 'Поделиться ссылкой',
    'online.lobby.start': 'Начать игру',
    'online.lobby.needMore': 'Нужен ещё игрок',
    'online.lobby.hostHint': 'Не закрывайте эту вкладку, пока идёт игра',
    'online.lobby.close': 'Закрыть стол',
    'online.lobby.leave': 'Выйти',
    'online.lobby.waitHost': 'Ждём, пока создатель начнёт',
    'online.lobby.full': 'Стол заполнен · ждём, пока создатель начнёт',
    'online.lobby.creator': 'Создатель',
    'online.lobby.you': 'Вы',
    'online.lobby.waiting': 'Ждём игрока…',
    'online.round': 'Раунд {n} из {m}',
    'online.table': 'Стол {code}',
    'online.yourTurn': 'Ваш ход',
    'online.turnOf': 'Ходит {name}',
    'online.waitOthers': 'Вы записали очки. Ждём остальных: {n}',
    'online.sent': 'Отправлено…',
    'online.waitConn': 'Ждём соединения…',
    'online.leave': 'Выйти из-за стола',
    'online.stay': 'Остаться',
    'online.creatorNote': 'Вы создатель: не закрывайте эту вкладку, пока идёт игра',
    'online.st.left': 'Вышел',
    'online.st.finished': 'Закончил',
    'online.st.silent': 'Не отвечает…',
    'online.st.waits': 'Ждёт',
    'online.st.scored': 'Записал(а) очки',
    'online.st.thinks': 'Думает',
    'online.st.thinksSec': 'Думает · {n} с',
    'online.st.rolls': 'Бросков: {n}',
    'online.ask.title': 'Вы ещё играете?',
    'online.ask.secs': 'секунд до сдачи: без ответа вы сдадитесь',
    'online.ask.yes': 'Да, играю',
    'online.ask.leave': 'Выйти из-за стола',
    'online.over.title': 'Игра окончена',
    'online.over.alone': 'Остальные игроки вышли',
    'online.over.leave': 'К выбору стола',
    'online.out.title': 'Вы выбыли из-за стола',
    'online.out.text': 'Вы не отвечали 2 минуты, поэтому сдались.',
    'online.out.btn': 'К выбору стола',
    'online.confirmLeave.title': 'Выйти из-за стола?',
    'online.confirmLeave.text': 'Вы выбудете из партии, очки останутся в таблице.',
    'online.confirmClose.title': 'Закрыть стол?',
    'online.confirmClose.text': 'Если вы выйдете, стол закроется для всех.',
    'online.banner.offline': 'Нет связи, переподключаемся…',
    'online.banner.back': 'Связь восстановлена',
    'online.banner.relogin': 'Нужно войти снова',
    'online.banner.reloginBtn': 'Войти',
    'rules.online.title': 'Онлайн',
    'rules.online.text': 'Одновременно: все бросают и записывают очки в своём темпе, но следующий раунд начинается, когда очки записали все. По очереди: ходит один игрок за другим.'
  };
  Object.keys(texts).forEach(function (k) { root.LOCALES.ru = root.LOCALES.ru || {}; root.LOCALES.ru[p + k] = texts[k]; });
})(typeof window !== 'undefined' ? window : globalThis);
